// <auto-generated />
using System;
using LatihanWebApi.Database.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LatihanWebApi.Database.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LatihanWebApi.Database.Models.Students", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<int>("Nisn")
                        .HasColumnType("int")
                        .HasColumnName("nisn");

                    b.Property<string>("Parent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parent");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("NVarchar(50)")
                        .HasColumnName("student_name");

                    b.HasKey("StudentId");

                    b.ToTable("Student", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
